<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="apartment" params="name">

  <!-- wall_00 -->
  <link name="wall_00">
    <xacro:box_inertial x="${wall_depth}" y="${size_d+0.18+0.35}" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_d+0.18+0.35} ${size_z_wall1}" />
      </geometry>
      <material name="DIAG/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_d+0.18+0.35} ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_00">
    <material>wall_floor_05</material>
  </gazebo>

  <joint name="joint_wall_00" type="fixed">
    <origin xyz="${-size_total_x/2+dist_axis_x-wall_depth} ${(size_total_y/2-size_d/2+0.1-dist_axis_y)+0.175} ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_00" />
  </joint>

  <!-- wall_01 -->
  <link name="wall_01_part1">
    <xacro:box_inertial x="${size_b}" y="0.001" z="0.90" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size=" ${size_b} 0.001 0.90" />
      </geometry>
      <material name="DIAG/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${size_b} 0.001 0.90" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_01_part1">
    <material>kitchen_wall_with_heating</material>
  </gazebo>

  <joint name="joint_wall_01_part1" type="fixed">
    <origin xyz="${dist_axis_x} ${size_total_y/2-dist_axis_y+window_depth+0.02} 0.45" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_01_part1" />
  </joint>

  <!-- wall_01_part2 -->
  <link name="wall_01_part2">
    <xacro:box_inertial x="${size_b}" y="0.35" z="0.90" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size=" ${size_b} 0.35 0.90" />
      </geometry>
      <material name="DIAG/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${size_b} 0.35 0.90" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_01_part2">
    <material>kitchen_window_board</material>
  </gazebo>

  <joint name="joint_wall_01_part2" type="fixed">
    <origin xyz="${dist_axis_x} ${size_total_y/2-dist_axis_y+window_depth+0.195} 0.45" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_01_part2" />
  </joint>

  <!-- wall_01_little_glas -->
  <link name="wall_01_little_glas">
    <xacro:box_inertial x="0.02" y="0.35" z="2.70" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.02 0.35 2.70" />
      </geometry>
      <material name="DIAG/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.02 0.35 2.70" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_01_little_glas">
    <material>kitchen_wall_with_windows</material>
  </gazebo>

  <joint name="joint_wall_01_little_glas" type="fixed">
    <origin xyz="3.5 ${size_total_y/2-dist_axis_y+window_depth+0.195} 1.35" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_01_little_glas" />
  </joint>

  <!-- wall_01_part3 -->
  <link name="wall_01_part3">
    <xacro:box_inertial x="${size_b}" y="${window_depth}" z="1.80" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size=" ${size_b} ${window_depth} 1.80" />
      </geometry>
      <material name="DIAG/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${size_b} ${window_depth} 1.80" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_01_part3">
    <material>kitchen_wall_with_windows</material>
  </gazebo>

  <joint name="joint_wall_01_part3" type="fixed">
    <origin xyz="${dist_axis_x} ${size_total_y/2-dist_axis_y+window_depth+0.44} 1.80" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_01_part3" />
  </joint>

  <!-- wall_02 -->
  <link name="wall_02">
    <xacro:box_inertial x="${wall_depth}" y="${size_a+0.35}" z="${size_z_wall2}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_a+0.35} ${size_z_wall2}" />
      </geometry>
      <material name="DIAG/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_a+0.35} ${size_z_wall2}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_02">
    <material>wall_floor_05</material>
  </gazebo>

  <joint name="joint_wall_02" type="fixed">
    <origin xyz="${size_total_x/2+dist_axis_x+wall_depth} ${(size_total_y/2-size_a/2+0.15-dist_axis_y)+0.175} ${size_z_wall2/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_02" />
  </joint>

  <!-- wall_03 -->
  <link name="wall_03">
    <xacro:box_inertial x="${window_depth}" y="1.55" z="${size_z_wall2}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size=" ${window_depth} 1.55 ${size_z_wall2}" />
      </geometry>
      <material name="DIAG/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${window_depth} 1.55 ${size_z_wall2}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_03">
    <material>emergencyExit_window_left</material>
  </gazebo>

  <joint name="joint_wall_03" type="fixed">
    <origin xyz="${size_total_x/2+dist_axis_x+0.55+window_depth/2} ${0.6-dist_axis_y} ${size_z_wall2/2}" rpy="0 0 0.785398" />
    <parent link="world" />
    <child link="wall_03" />
  </joint>

  <!-- wall_04 -->
  <link name="wall_04">
    <xacro:box_inertial x="${window_depth}" y="1.6" z="${size_z_wall2}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${window_depth} 1.6 ${size_z_wall2}" />
      </geometry>
      <material name="DIAG/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${window_depth} 1.6 ${size_z_wall2}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_04">
    <material>emergencyExit_window_right</material>
  </gazebo>

  <joint name="joint_wall_04" type="fixed">
    <origin xyz="${size_total_x/2+dist_axis_x+0.61+window_depth/2} ${-0.54-dist_axis_y} ${size_z_wall2/2}" rpy="0 0 -0.785398" />
    <parent link="world" />
    <child link="wall_04" />
  </joint>

  <!-- wall_05 -->
  <link name="wall_05">
    <xacro:box_inertial x="${wall_depth}" y="${size_a}" z="${size_z_wall2}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_a} ${size_z_wall2}" />
      </geometry>
      <material name="DIAG/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_a} ${size_z_wall2}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_05">
    <material>wall_floor_05</material>
  </gazebo>

  <joint name="joint_wall_05" type="fixed">
    <origin xyz="${size_total_x/2+dist_axis_x+wall_depth} ${-size_total_y/2+size_a/2-0.15-dist_axis_y} ${size_z_wall2/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_05" />
  </joint>

  <!-- wall_06 -->
  <link name="wall_06">
    <xacro:box_inertial x="${size_b}" y="${window_depth}" z="${size_z_wall2}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size=" ${size_b} ${window_depth} ${size_z_wall2}" />
      </geometry>
      <material name="DIAG/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${size_b} ${window_depth+0.02} ${size_z_wall2}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_06">
    <material>wall_livingroom1</material>
  </gazebo>

  <joint name="joint_wall_06" type="fixed">
    <origin xyz="${+dist_axis_x-0.05} ${-size_total_y/2-dist_axis_y-window_depth} ${size_z_wall2/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_06" />
  </joint>

  <!-- wall_07 -->
  <link name="wall_07">
    <xacro:box_inertial x="${wall_depth}" y="${size_a}" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_a} ${size_z_wall1}" />
      </geometry>
      <material name="DIAG/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_a} ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_07">
    <material>wall_floor_05</material>
  </gazebo>

  <joint name="joint_wall_07" type="fixed">
    <origin xyz="${-size_total_x/2+dist_axis_x-wall_depth} ${-size_total_y/2+size_a/2-0.1-dist_axis_y} ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_07" />
  </joint>

  <!-- door_00 -->
  <link name="door_00">
    <xacro:box_inertial x="0.04" y="0.62" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.04 0.62 ${size_z_wall1}" />
      </geometry>
      <material name="DIAG/Transparent"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.04 0.62 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="door_00">
    <material>DIAG/Wall2</material>
  </gazebo>

  <joint name="joint_door_00" type="fixed">
    <origin xyz="${-size_total_x/2+dist_axis_x-wall_depth} ${1.22-dist_axis_y} ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="door_00" />
  </joint>

  <!-- door_01 -->
  <link name="door_01">
    <xacro:box_inertial x="0.04" y="0.62" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.04 0.62 ${size_z_wall1}" />
      </geometry>
      <material name="DIAG/Transparent"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.04 0.62 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="door_01">
    <material>DIAG/Wall2</material>
  </gazebo>

  <joint name="joint_door_01" type="fixed">
    <origin xyz="${-size_total_x/2+dist_axis_x-wall_depth} ${-0.68-dist_axis_y} ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="door_01" />
  </joint>

  </xacro:macro>

</robot>
