<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="diag_walls" params="name">

  <!-- wall_00 -->
  <link name="wall_00">
    <xacro:box_inertial x="${wall_depth}" y="${size_a}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_a} ${wall_height}" />
      </geometry>
      <material name="DIAG/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_a} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_00">
    <material>wall_floor_05</material>
  </gazebo>

  <joint name="joint_wall_00" type="fixed">
    <origin xyz="0 0 ${wall_height/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_00" />
  </joint>


  <!-- wall_01 -->
  <link name="wall_01">
    <xacro:box_inertial x="${wall_depth}" y="${size_b}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_b} ${wall_height}" />
      </geometry>
      <material name="DIAG/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_b} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_01">
    <material>wall_floor_04</material>
  </gazebo>

  <joint name="joint_wall_01" type="fixed">
    <origin xyz="${size_b/2} ${size_a/2} ${wall_height/2}" rpy="0 0 1.57" />
    <parent link="world" />
    <child link="wall_01" />
  </joint>

  <!-- wall_02 -->
  <link name="wall_02">
    <xacro:box_inertial x="${wall_depth}" y="${size_a}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_a} ${wall_height}" />
      </geometry>
      <material name="DIAG/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_a} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_02">
    <material>wall_floor_04</material>
  </gazebo>

  <joint name="joint_wall_02" type="fixed">
    <origin xyz="${size_b} 0 ${wall_height/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_02" />
  </joint>

  <!-- wall_03 -->
  <link name="wall_03">
    <xacro:box_inertial x="${wall_depth}" y="${size_b}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_b} ${wall_height}" />
      </geometry>
      <material name="DIAG/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_b} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_03">
    <material>wall_floor_04</material>
  </gazebo>

  <joint name="joint_wall_03" type="fixed">
    <origin xyz="${size_b/2} ${-size_a/2} ${wall_height/2}" rpy="0 0 1.57" />
    <parent link="world" />
    <child link="wall_03" />
  </joint>

  <!-- wall_04 -->
  <link name="wall_04">
    <xacro:box_inertial x="${wall_depth}" y="${size_c}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_c} ${wall_height}" />
      </geometry>
      <material name="DIAG/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_c} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_04">
    <material>wall_floor_04</material>
  </gazebo>

  <joint name="joint_wall_04" type="fixed">
    <origin xyz="${size_c/2} ${-size_a/2+4} ${wall_height/2}" rpy="0 0 1.57" />
    <parent link="world" />
    <child link="wall_04" />
  </joint>

  <!-- wall_05 -->
  <link name="wall_05">
    <xacro:box_inertial x="${wall_depth}" y="${size_d}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_d} ${wall_height}" />
      </geometry>
      <material name="DIAG/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_d} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_05">
    <material>wall_floor_04</material>
  </gazebo>

  <joint name="joint_wall_05" type="fixed">
    <origin xyz="${size_b - size_d/2} ${-size_a/2+4} ${wall_height/2}" rpy="0 0 1.57" />
    <parent link="world" />
    <child link="wall_05" />
  </joint>


  <!-- wall_06 -->
  <link name="wall_06">
    <xacro:box_inertial x="${wall_depth}" y="${size_c}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_c} ${wall_height}" />
      </geometry>
      <material name="DIAG/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_c} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_06">
    <material>wall_floor_04</material>
  </gazebo>

  <joint name="joint_wall_06" type="fixed">
    <origin xyz="${size_c/2} ${-size_a/2+7} ${wall_height/2}" rpy="0 0 1.57" />
    <parent link="world" />
    <child link="wall_06" />
  </joint>

  <!-- wall_07 -->
  <link name="wall_07">
    <xacro:box_inertial x="${wall_depth}" y="${size_d}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_d} ${wall_height}" />
      </geometry>
      <material name="DIAG/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${size_d} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_07">
    <material>wall_floor_04</material>
  </gazebo>

  <joint name="joint_wall_07" type="fixed">
    <origin xyz="${size_b - size_d/2} ${-size_a/2+7} ${wall_height/2}" rpy="0 0 1.57" />
    <parent link="world" />
    <child link="wall_07" />
  </joint>

  </xacro:macro>

</robot>
